# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bouncingBallsMessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62ouncingBallsMessages.proto\"G\n\x0bstateUpdate\x12\x14\n\x05\x62\x61lls\x18\x01 \x03(\x0b\x32\x05.Ball\x12\x11\n\tballCount\x18\x02 \x01(\x05\x12\x0f\n\x07timeUTC\x18\x03 \x01(\x05\"3\n\x04\x42\x61ll\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01r\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bouncingBallsMessages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATEUPDATE._serialized_start=31
  _STATEUPDATE._serialized_end=102
  _BALL._serialized_start=104
  _BALL._serialized_end=155
# @@protoc_insertion_point(module_scope)
