// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bouncingBallsMessages.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_bouncingBallsMessages_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_bouncingBallsMessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_bouncingBallsMessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_bouncingBallsMessages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_bouncingBallsMessages_2eproto;
class Ball;
struct BallDefaultTypeInternal;
extern BallDefaultTypeInternal _Ball_default_instance_;
class stateUpdate;
struct stateUpdateDefaultTypeInternal;
extern stateUpdateDefaultTypeInternal _stateUpdate_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Ball final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Ball) */ {
 public:
  inline Ball() : Ball(nullptr) {}
  ~Ball() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Ball(
      ::google::protobuf::internal::ConstantInitialized);

  inline Ball(const Ball& from) : Ball(nullptr, from) {}
  inline Ball(Ball&& from) noexcept
      : Ball(nullptr, std::move(from)) {}
  inline Ball& operator=(const Ball& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ball& operator=(Ball&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ball& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ball* internal_default_instance() {
    return reinterpret_cast<const Ball*>(
        &_Ball_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Ball& a, Ball& b) { a.Swap(&b); }
  inline void Swap(Ball* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ball* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ball* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Ball>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Ball& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Ball& from) { Ball::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Ball* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Ball"; }

 protected:
  explicit Ball(::google::protobuf::Arena* arena);
  Ball(::google::protobuf::Arena* arena, const Ball& from);
  Ball(::google::protobuf::Arena* arena, Ball&& from) noexcept
      : Ball(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kRFieldNumber = 4,
    kIdFieldNumber = 1,
  };
  // double x = 2;
  void clear_x() ;
  double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 3;
  void clear_y() ;
  double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // double r = 4;
  void clear_r() ;
  double r() const;
  void set_r(double value);

  private:
  double _internal_r() const;
  void _internal_set_r(double value);

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Ball)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Ball_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Ball& from_msg);
    double x_;
    double y_;
    double r_;
    ::int32_t id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bouncingBallsMessages_2eproto;
};
// -------------------------------------------------------------------

class stateUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:stateUpdate) */ {
 public:
  inline stateUpdate() : stateUpdate(nullptr) {}
  ~stateUpdate() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR stateUpdate(
      ::google::protobuf::internal::ConstantInitialized);

  inline stateUpdate(const stateUpdate& from) : stateUpdate(nullptr, from) {}
  inline stateUpdate(stateUpdate&& from) noexcept
      : stateUpdate(nullptr, std::move(from)) {}
  inline stateUpdate& operator=(const stateUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline stateUpdate& operator=(stateUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const stateUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const stateUpdate* internal_default_instance() {
    return reinterpret_cast<const stateUpdate*>(
        &_stateUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(stateUpdate& a, stateUpdate& b) { a.Swap(&b); }
  inline void Swap(stateUpdate* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(stateUpdate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  stateUpdate* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<stateUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const stateUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const stateUpdate& from) { stateUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(stateUpdate* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "stateUpdate"; }

 protected:
  explicit stateUpdate(::google::protobuf::Arena* arena);
  stateUpdate(::google::protobuf::Arena* arena, const stateUpdate& from);
  stateUpdate(::google::protobuf::Arena* arena, stateUpdate&& from) noexcept
      : stateUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBallsFieldNumber = 1,
    kBallCountFieldNumber = 2,
    kTimeUTCFieldNumber = 3,
  };
  // repeated .Ball balls = 1;
  int balls_size() const;
  private:
  int _internal_balls_size() const;

  public:
  void clear_balls() ;
  ::Ball* mutable_balls(int index);
  ::google::protobuf::RepeatedPtrField<::Ball>* mutable_balls();

  private:
  const ::google::protobuf::RepeatedPtrField<::Ball>& _internal_balls() const;
  ::google::protobuf::RepeatedPtrField<::Ball>* _internal_mutable_balls();
  public:
  const ::Ball& balls(int index) const;
  ::Ball* add_balls();
  const ::google::protobuf::RepeatedPtrField<::Ball>& balls() const;
  // int32 ballCount = 2;
  void clear_ballcount() ;
  ::int32_t ballcount() const;
  void set_ballcount(::int32_t value);

  private:
  ::int32_t _internal_ballcount() const;
  void _internal_set_ballcount(::int32_t value);

  public:
  // int32 timeUTC = 3;
  void clear_timeutc() ;
  ::int32_t timeutc() const;
  void set_timeutc(::int32_t value);

  private:
  ::int32_t _internal_timeutc() const;
  void _internal_set_timeutc(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:stateUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_stateUpdate_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const stateUpdate& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Ball > balls_;
    ::int32_t ballcount_;
    ::int32_t timeutc_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bouncingBallsMessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// stateUpdate

// repeated .Ball balls = 1;
inline int stateUpdate::_internal_balls_size() const {
  return _internal_balls().size();
}
inline int stateUpdate::balls_size() const {
  return _internal_balls_size();
}
inline void stateUpdate::clear_balls() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.balls_.Clear();
}
inline ::Ball* stateUpdate::mutable_balls(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:stateUpdate.balls)
  return _internal_mutable_balls()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Ball>* stateUpdate::mutable_balls()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:stateUpdate.balls)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_balls();
}
inline const ::Ball& stateUpdate::balls(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:stateUpdate.balls)
  return _internal_balls().Get(index);
}
inline ::Ball* stateUpdate::add_balls() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Ball* _add = _internal_mutable_balls()->Add();
  // @@protoc_insertion_point(field_add:stateUpdate.balls)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Ball>& stateUpdate::balls() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:stateUpdate.balls)
  return _internal_balls();
}
inline const ::google::protobuf::RepeatedPtrField<::Ball>&
stateUpdate::_internal_balls() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.balls_;
}
inline ::google::protobuf::RepeatedPtrField<::Ball>*
stateUpdate::_internal_mutable_balls() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.balls_;
}

// int32 ballCount = 2;
inline void stateUpdate::clear_ballcount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ballcount_ = 0;
}
inline ::int32_t stateUpdate::ballcount() const {
  // @@protoc_insertion_point(field_get:stateUpdate.ballCount)
  return _internal_ballcount();
}
inline void stateUpdate::set_ballcount(::int32_t value) {
  _internal_set_ballcount(value);
  // @@protoc_insertion_point(field_set:stateUpdate.ballCount)
}
inline ::int32_t stateUpdate::_internal_ballcount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ballcount_;
}
inline void stateUpdate::_internal_set_ballcount(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ballcount_ = value;
}

// int32 timeUTC = 3;
inline void stateUpdate::clear_timeutc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeutc_ = 0;
}
inline ::int32_t stateUpdate::timeutc() const {
  // @@protoc_insertion_point(field_get:stateUpdate.timeUTC)
  return _internal_timeutc();
}
inline void stateUpdate::set_timeutc(::int32_t value) {
  _internal_set_timeutc(value);
  // @@protoc_insertion_point(field_set:stateUpdate.timeUTC)
}
inline ::int32_t stateUpdate::_internal_timeutc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timeutc_;
}
inline void stateUpdate::_internal_set_timeutc(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeutc_ = value;
}

// -------------------------------------------------------------------

// Ball

// int32 id = 1;
inline void Ball::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t Ball::id() const {
  // @@protoc_insertion_point(field_get:Ball.id)
  return _internal_id();
}
inline void Ball::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Ball.id)
}
inline ::int32_t Ball::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Ball::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// double x = 2;
inline void Ball::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline double Ball::x() const {
  // @@protoc_insertion_point(field_get:Ball.x)
  return _internal_x();
}
inline void Ball::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Ball.x)
}
inline double Ball::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Ball::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 3;
inline void Ball::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline double Ball::y() const {
  // @@protoc_insertion_point(field_get:Ball.y)
  return _internal_y();
}
inline void Ball::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Ball.y)
}
inline double Ball::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Ball::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// double r = 4;
inline void Ball::clear_r() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.r_ = 0;
}
inline double Ball::r() const {
  // @@protoc_insertion_point(field_get:Ball.r)
  return _internal_r();
}
inline void Ball::set_r(double value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:Ball.r)
}
inline double Ball::_internal_r() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.r_;
}
inline void Ball::_internal_set_r(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.r_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_bouncingBallsMessages_2eproto_2epb_2eh
